[package]
name = "RustyPIX"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
rand = "0.8"
rustacuda = "0.1"
rustacuda_core = "0.1"
rustacuda_derive = "0.1"
